### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by arisops** [AnEntrypoint/hyper-nat#1]
Can you say a bit more about this

To build the exe yourself, use a nexe compatible version of node, then run nexe in the path, remember to copy the static builds for sodium and udx

Can you point to where to get those? Great project and thank you!

**Comment by lanmower** [comment]
hey hey :), thank you for your interest!

aah ok, so remember if you can't build the exe, you can still download it from releases, I've just fixed the last release noticed there was missing files...

if you want to see which files need to be copied (from the projects node_modules directory) you can also look at the release because it will show you which files are required, they exist in the prebuilds directory of their respective requirements... if I remember correctly udx-native, utp-native sodium-native and keypear/node_modules/sodium-native was the affected packages, it does ask for them when you run the program too when they're missing.

**Comment by lanmower** [comment]
Alright, I've just updated the release with a tested version, if you go look inside its node_modules directory you'll see the various native builds you need to rescue from the projects node_modules install

**Comment by lanmower** [comment]
As a last note the nexe I've tested was with portable node 14.15.3 to avoid having to build anything extra

**Comment by lanmower** [comment]
ummmm and yeah I looked at your account, looks like you're into metaverse stuff pleased to meet you...

we tinker in this discord https://discord.gg/an-entrypoint-367741339393327104

**Comment by lanmower** [comment]
btw a perused your profile, you're on the ball with research I like it :)

**Comment by arisops** [comment]
Thank you for setting that up!
